[deploy]
bucket = 'cfn-artifacts-opeoginni'
region = 'eu-central-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://opeoginni.cloud'
EnvBackendUrl = 'https://api.opeoginni.cloud'
DDBMessageTable = 'CrdDdb-DynamoDBTable-OU3TSZYS41M2'