[deploy]
bucket = 'cfn-artifacts-opeoginni'
region = 'eu-central-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'OpeOginni/aws-bootcamp-cruddur-2023'
ArtifactBucketName = 'codepipeline-cruddur-artifacts-opeoginni'

